Repository GEOS-ESM/GEOS-S2S-3, pull requests merged in 2024-10, with the labels that each got.

#4 Feature/mfmehari/new dataatm in s2sv3
  CHANGELOG.md
  src/GEOSgcs_GridComp/GEOSgcm_GridComp/GEOS_GcmGridComp.F90
  src/GEOSgcs_GridComp/GEOSgcm_GridComp/GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOS_SurfaceGridComp.F90
  src/GEOSgcs_GridComp/GEOSgcm_GridComp/GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOSsaltwater_GridComp/GEOS_SaltWaterGridComp.F90
  src/GEOSgcs_GridComp/GEOSgcm_GridComp/GEOSdataatm_GridComp/CORE_NYF_Data_AtmForcings_ExtData.rc
  src/GEOSgcs_GridComp/GEOSgcm_GridComp/GEOSdataatm_GridComp/GEOS_DataAtmGridComp.F90
  src/GEOSgcs_GridComp/GEOSgcm_GridComp/GEOSdataatm_GridComp/GNUmakefile
  src/GEOSgcs_GridComp/GEOSgcm_GridComp/GEOSdataatm_GridComp/OASIM/src/clrtrans.F90
  src/GEOSgcs_GridComp/GEOSgcm_GridComp/GEOSdataatm_GridComp/OASIM/src/comlte.h
  src/GEOSgcs_GridComp/GEOSgcm_GridComp/GEOSdataatm_GridComp/OASIM/src/definebio.h
  src/GEOSgcs_GridComp/GEOSgcm_GridComp/GEOSdataatm_GridComp/OASIM/src/lidatatm.F90
  src/GEOSgcs_GridComp/GEOSgcm_GridComp/GEOSdataatm_GridComp/OASIM/src/setsfclte.F90
  src/GEOSgcs_GridComp/GEOSgcm_GridComp/GEOSdataatm_GridComp/OASIM/src/sfcirr.F90
  src/GEOSgcs_GridComp/GEOSgcm_GridComp/GEOSdataatm_GridComp/OASIM/src/slingo.F90
  src/GEOSgcs_GridComp/GEOSgcm_GridComp/GEOSdataatm_GridComp/OBIO_Data_AtmForcings_ExtData.rc
  src/GEOSgcs_GridComp/GEOSgcm_GridComp/GEOSdataatm_GridComp/cube_sphere.F90
  src/GEOSgcs_GridComp/GEOSgcm_GridComp/GEOSdataatm_GridComp/ncar_ocean_fluxes.F90
  src/GEOSgcs_GridComp/GEOSgcm_GridComp/GEOSogcm_GridComp/GEOS_OgcmGridComp.F90
  src/GEOSgcs_GridComp/GEOSgcm_GridComp/GEOSogcm_GridComp/GEOSoceanbiogeochem_GridComp/GEOS_OceanbiogeochemGridComp.F90
Labels: enhancement, 0 diff

#8 Added support for constant hydrometeor concentratrion
  src/Applications/GEOSgcm_App/gcm_setup
  src/GEOSgcs_GridComp/GEOSgcm_GridComp/GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/CLDPARAMS.F90
  src/GEOSgcs_GridComp/GEOSgcm_GridComp/GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/GEOS_MoistGridComp.F90
  src/GEOSgcs_GridComp/GEOSgcm_GridComp/GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/RASPARAMS.F90
  src/GEOSgcs_GridComp/GEOSgcm_GridComp/GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/WSUB_ExtData.rc
  src/GEOSgcs_GridComp/GEOSgcm_GridComp/GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/cldmacro.F90
  src/GEOSgcs_GridComp/GEOSgcm_GridComp/GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/cldwat2m_micro.F90
  src/GEOSgcs_GridComp/GEOSgcm_GridComp/GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/ras.F90
Labels: Skip Changelog, enhancement, 0 diff

#10 Adding new perturbation code for NRT
  src/Applications/FCSTS2S3_Etc/PERTV3_NRT/AtmPertsV3/alpha10_rho_DJF_9ddiffs_V3_GiOcean.txt
  src/Applications/FCSTS2S3_Etc/PERTV3_NRT/AtmPertsV3/alpha10_rho_DJF_9ddiffs_V3_eh020.txt
  src/Applications/FCSTS2S3_Etc/PERTV3_NRT/AtmPertsV3/alpha10_rho_JJA_9ddiffs_V3_GiOcean.txt
  src/Applications/FCSTS2S3_Etc/PERTV3_NRT/AtmPertsV3/alpha10_rho_JJA_9ddiffs_V3_eh020.txt
  src/Applications/FCSTS2S3_Etc/PERTV3_NRT/AtmPertsV3/alpha10_rho_MAM_9ddiffs_V3_GiOcean.txt
  src/Applications/FCSTS2S3_Etc/PERTV3_NRT/AtmPertsV3/alpha10_rho_MAM_9ddiffs_V3_eh020.txt
  src/Applications/FCSTS2S3_Etc/PERTV3_NRT/AtmPertsV3/alpha10_rho_SON_9ddiffs_V3_GiOcean.txt
  src/Applications/FCSTS2S3_Etc/PERTV3_NRT/AtmPertsV3/alpha10_rho_SON_9ddiffs_V3_eh020.txt
  src/Applications/FCSTS2S3_Etc/PERTV3_NRT/OcnPertsV3/ocn_alpha10_DJF_9ddiffs_5levs_V3_GiOcean.txt
  src/Applications/FCSTS2S3_Etc/PERTV3_NRT/OcnPertsV3/ocn_alpha10_DJF_9ddiffs_5levs_V3_eh020.txt
  src/Applications/FCSTS2S3_Etc/PERTV3_NRT/OcnPertsV3/ocn_alpha10_JJA_9ddiffs_5levs_V3_GiOcean.txt
  src/Applications/FCSTS2S3_Etc/PERTV3_NRT/OcnPertsV3/ocn_alpha10_JJA_9ddiffs_5levs_V3_eh020.txt
  src/Applications/FCSTS2S3_Etc/PERTV3_NRT/OcnPertsV3/ocn_alpha10_MAM_9ddiffs_5levs_V3_GiOcean.txt
  src/Applications/FCSTS2S3_Etc/PERTV3_NRT/OcnPertsV3/ocn_alpha10_MAM_9ddiffs_5levs_V3_eh020.txt
  src/Applications/FCSTS2S3_Etc/PERTV3_NRT/OcnPertsV3/ocn_alpha10_SON_9ddiffs_5levs_V3_GiOcean.txt
  src/Applications/FCSTS2S3_Etc/PERTV3_NRT/OcnPertsV3/ocn_alpha10_SON_9ddiffs_5levs_V3_eh020.txt
  src/Applications/FCSTS2S3_Etc/PERTV3_NRT/README
  src/Applications/FCSTS2S3_Etc/PERTV3_NRT/perturbation_config.yaml
  src/Applications/FCSTS2S3_Etc/PERTV3_NRT/run_april_atmo.csh
  src/Applications/FCSTS2S3_Etc/PERTV3_NRT/run_perturbations_V3.py
Labels: Skip Changelog, enhancement
