Repository GEOS-ESM/GEOS-S2S-3, pull requests merged in 2025-04, with the labels that each got.

#24 Remove SLES12 mentions at NCCS
  src/Applications/GEOSgcm_App/gcm_setup
  src/g5_modules
  src/parallel_build.csh
Labels: Skip Changelog, 0 diff

#28 Feature/vruizxom/production tag update
  src/Applications/GEOSgcm_App/AGCM.rc.tmpl
  src/Applications/GEOSgcm_App/gcm_run.j
  src/Applications/GEOSgcm_App/gcm_setup
  src/Applications/GEOSgcm_App/ocean_das_config.tmpl
  src/Applications/UMD_Etc/UMD_utils/ocean_obs.py
Labels: Skip Changelog

#27 Update g5_modules to use Intel 19
  src/g5_modules
Labels: Skip Changelog

#30 Do not set psm3 on Cascade Lake at NCCS
  src/Applications/GEOSgcm_App/gcm_setup
Labels: Skip Changelog, 0 diff

#32 Fix a bug generating SETENV.commands in gcm_setup
  src/Applications/GEOSgcm_App/gcm_setup
Labels: Skip Changelog, bug

#31 Fix bad csh-making-csh in gcm_setup
  src/Applications/GEOSgcm_App/gcm_setup
Labels: Skip Changelog, 0 diff

#29 Change ncap2 modulefile
  src/g5_modules
Labels: Skip Changelog, enhancement, 0 diff
